### ISSUE TITLE
Helm chart installation notes need to be fixed

### ISSUE THREAD

**Issue by mailtosanjeev** [podtato-head/podtato-head#125]
After installing helm chart on a local kubernetes cluster, i received the output pasted below. The command references a service names "podtato-head-main" but what is deployed is "podtato-main". 

```
NOTES:
1. Get the application URL by running these commands:
     NOTE: It may take a few minutes for the LoadBalancer IP to be available.
           You can watch the status of by running 'kubectl get --namespace podtato svc -w podtato-head-main'
  export SERVICE_IP=$(kubectl get svc --namespace podtato podtato-head-main --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
  echo http://$SERVICE_IP:9000
```

**Comment by joshgav** [comment]
Thanks @mailtosanjeev. Looks like parts of the repo were using "podtato-head" and parts were using "podtato" as the base name. I updated it in #137 to use "podtato-head" everywhere, PTAL.
