### ISSUE TITLE
Update Keptn example

### ISSUE THREAD

**Issue by TannerGabriel** [podtato-head/podtato-head#139]
The current Keptn delivery example located in `delivery/keptn`  does not work after #129 and needs to be updated. There might be the need to finish #78 before starting this issue.

## Definition of done

- [ ] Update example to work with current Podtato-head
- [ ] Update Keptn and all its dependencies to the newest installation

**Comment by joshgav** [comment]
Thanks @TannerGabriel, I think this _is_ #78 🤔. The keptn scenario has never been updated for "multiple services".

For a while though we were maintaining the original "single service" codebase here too in a directory `./podtatoserver`. That codebase was removed in #129. Maybe we should reconsider that and reinstate the "single service" too?

**Comment by TannerGabriel** [comment]
@joshgav Yes, I think it would be great if we could reinstate the "single service" codebase. If it is alright with you, I could submit a PR for this.

**Comment by TannerGabriel** [comment]
After taking a closer look at the current implementation and trying it out myself, there are a few remaining questions before I can start with the implementation.

1. Before the updates made in #129 `podato-head` had three versions (v0.1.0, v0.1.1 and v0.1.2) and we used the v0.1.2 version for the slow build. Is this still the case with the different parts, or did the versioning change?
2. After trying out the new update, I ran into some problems starting the different "parts" (head, arms, etc.) where the entry image was trying to access the "parts" on port `900x`, but when starting a "part" it would serve the content on port `9000` (`going to serve on port 9000`). Is there some particular pattern to follow when starting the different parts, or is this still an error that needs to be addressed?

Maybe we should also consider documenting the two topics above.

**Comment by joshgav** [comment]
Thanks @TannerGabriel, answers:

1. In the microservices project there aren't multiple versions within one release as in the monolith. Instead, alternate part numbers are selected dynamically by setting the env var `PODTATO_PART_NUMBER` for the container. We should document this more clearly :+1:, see also #140.

    The versions of the microservices images are the current version of the podtato-head project itself (i.e. `0.2` today). 

    If you'd like to demonstrate a slow build can we propose a new way?

2. The images/pods all serve on port 9000 by default; the entry service reaches them via K8s Services which listen on the 900x ports and translate to the internal port (9000) on each Pod (see the delivery examples). I don't think this is a bug, but I think there's room for a more dynamic service discovery mechanism so alternate addresses could be injected. The discovery system is an interface so other implementations can be added: <https://github.com/podtato-head/podtato-head/blob/main/podtato-head/pkg/services/service_discoverer.go>.

**Comment by joshgav** [comment]
Hi @TannerGabriel, also PTAL at #142, should we add the monolith example back?
