### ISSUE TITLE
image pull fails because unauthorized

### ISSUE THREAD

**Issue by bygui86** [podtato-head/podtato-head#148]
Hi guys,

I'm trying to pull podtato-head container images but I keep receiving this error:
```
Error response from daemon: Head "https://ghcr.io/v2/podtato-head/right-leg/manifests/0.2.1": unauthorized
```

I tried with simple `docker pull ghcr.io/podtato-head/right-leg:0.2.1` and deploying on minikube using both `delivery/kubectl` folder and `delivery/kustomize` folder.

Can you please explain me how to make those work?

**Comment by bygui86** [comment]
I tried also `make bulld-images` setting github user and token... tons of errors...

Can you please make images available somehow? Maybe docker hub would be easier...

**Comment by joshgav** [comment]
Hi @bygui86. We've made the images public now, they're at <https://github.com/orgs/podtato-head/packages?repo_name=podtato-head>. Can you please try again and let us know how it goes?

Re the error:

```
podtato-head/build/build_images.sh: line 41: source: /Users/mbaiguini/Downloads/WIP/podtato-head/podtato-head/podtato-head/build: is a directory
```

The line referred to is `source ${this_dir}/version.sh`, it looks like your shell/interpreter separated the dirname from the basename (file name). Can you try wrapping `${this_dir}/version.sh` in quotes? Not sure, but maybe that will help. FYI these scripts have only been tested on Linux and Bash.

The ensuing errors are a result of this failure - cause of that first failure you don't have a tag to apply to the images :O.

**Comment by bygui86** [comment]
Hi @joshgav thanks for your answer
I tried to pull images but still "denied"

```
$ docker pull ghcr.io/podtato-head/podtato-head/entry:0.2.6
Error response from daemon: Head "https://ghcr.io/v2/podtato-head/podtato-head/entry/manifests/0.2.6": denied: denied

$ docker pull ghcr.io/podtato-head/podtato-head/hat:0.2.6
Error response from daemon: Head "https://ghcr.io/v2/podtato-head/podtato-head/hat/manifests/0.2.6": denied: denied
```

Tried any other container image, for example

```
$ docker pull ubuntu
Using default tag: latest
latest: Pulling from library/ubuntu
08c01a0ec47e: Pull complete
Digest: sha256:669e010b58baf5beb2836b253c1fd5768333f0d1dbcb834f7c07a4dc93f474be
Status: Downloaded newer image for ubuntu:latest
docker.io/library/ubuntu:latest
```

I'm on macos using Docker Desktop 4.4.2 (73305)

About the scripts that doesn't work, I run that on macos with zsh but still I don't know why a shell should separate dirname from basename...
Anyway it would be enough having container images public and pullable... I tried to build images locally only as alternative...

**Comment by joshgav** [comment]
Thanks @bygui86. Can you try `docker pull ghcr.io/podtato-head/entry` or `entry:latest`? That is, just one "podtato-head".

Note I made a mistake in pointing you to _this_ repo's images in my last comment, sorry! The image you'll be pulling is in <https://github.com/orgs/podtato-head/packages/container/package/entry> and others there, at the _org_ level.

Thanks for bearing with us as we work out ghcr issues! A bit of a challenge...

**Comment by bygui86** [comment]
@joshgav unfortunately nothing works

```bash
$ docker pull ghcr.io/podtato-head/entry:sha256-64cf4b0ad5875ba925f9c1e10c09b93bc264af994c20448c5c6facb32c15b5d2.sig
Error response from daemon: Head "https://ghcr.io/v2/podtato-head/entry/manifests/sha256-64cf4b0ad5875ba925f9c1e10c09b93bc264af994c20448c5c6facb32c15b5d2.sig": denied: denied

$ docker pull ghcr.io/podtato-head/entry
Using default tag: latest
Error response from daemon: Head "https://ghcr.io/v2/podtato-head/entry/manifests/latest": denied: denied

$docker pull ghcr.io/podtato-head/entry:latest
Error response from daemon: Head "https://ghcr.io/v2/podtato-head/entry/manifests/latest": denied: denied
```

> Thanks for bearing with us as we work out ghcr issues! A bit of a challenge...
What about publish to Docker Hub? At least as first solution or mirror...

**Comment by joshgav** [comment]
@bygui86 `docker pull ghcr.io/podtato-head/entry` works for me from several workstations and VMs without authentication. Could it be you've authenticated to ghcr.io with a now-expired token? Perhaps try `docker logout ghcr.io` and then pull?

> What about publish to Docker Hub? At least as first solution or mirror...

That's worth considering, can you open an issue to discuss? At the moment we specify images with a full URL including host, like `ghcr.io/repo/image` so switching to another registry would mean changing those names, they'd have to become `docker.io/repo/image`. This could be a reason to investigate using _just_ short names like `repo/image` with `registries.conf`, see <https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md>.

**Comment by bygui86** [comment]
Thank you @joshgav, after running `docker logout ghcr.io` I was able to pull podtato-head with `docker pull ghcr.io/podtato-head/entry`.
But if podtato-head container images are public, why I'm forced to logout from ghcr in docker?
I'm logged in in docker hub and I'm perfectly able to pull all public images...

**Comment by joshgav** [comment]
Great news @bygui86! Happy it's working for you now.

I suspect the problem with your ghcr.io login is that the personal access token (PAT) you used to login has expired, and it's _worse_ to provide a bad token than not to provide a token at all. Your DockerHub token probably doesn't expire; but GitHub sets theirs to expire after 30 days by default.

**Comment by bygui86** [comment]
Good tip, I will review that!

Happy that this got solved! We can close this issue :)
