### ISSUE TITLE
make install-requirements on ARM64

### ISSUE THREAD

**Issue by AlexsJones** [podtato-head/podtato-head#154]
MacOS Monteray
Apple M1 Pro
Arm64

I will look into this at some point but this feels like a corner case with arm64.

```
✦9 ❯ make install-requirements
scripts/requirements.sh /usr/local/bin

installing trivy to /usr/local/bin
aquasecurity/trivy info checking GitHub for tag 'v0.21.1'
aquasecurity/trivy info found version: 0.21.1 for v0.21.1/macOS/ARM64
install: /usr/local/bin//trivy: Permission denied
scripts/requirements.sh: line 20: trivy: command not found

installing cosign to /usr/local/bin
curl: (23) Failure writing output to destination
chmod: /usr/local/bin/cosign: No such file or directory
```

**Comment by joshgav** [comment]
Sorry about that @AlexsJones. The script is minimum-viable for sure, I'll take a look again too. 

FYI it's used in the [release task](https://github.com/podtato-head/podtato-head/actions/workflows/microservices-release.yaml) to install trivy, cosign and skopeo.
