### ISSUE TITLE
podtato main not found error

### ISSUE THREAD

**Issue by sravanthnag** [podtato-head/podtato-head#159]
PORT=$(kubectl get services --namespace=podtato-kubectl podtato-main -ojsonpath='{.spec.ports[0].nodePort}')
Error from server (NotFound): services "podtato-main" not found

In whatever approach I try, this service is not available. I have downloaded the entire git also and tried to check but the podtato-main service is missing. Can you please check and revert

**Comment by joshgav** [comment]
Thanks @sravanthnag! The service should've been called `podtato-head-entry` (see https://github.com/podtato-head/podtato-head/blob/main/delivery/kubectl/manifest.yaml#L37), looks like there's a doc bug in the kubectl README.

In the meantime can you try: `PORT=$(kubectl get services --namespace=podtato-kubectl podtato-head-entry -ojsonpath='{.spec.ports[0].nodePort}')`?

**Comment by sravanthnag** [comment]
Thanks, this now works as expected
