### ISSUE TITLE
issue forking and developing when github username has mixcase

### ISSUE THREAD

**Issue by MxNxPx** [podtato-head/podtato-head#168]
When trying to develop locally I run into issues because my github username (MxNxPx) contains mixcase and the repo that is used in github requires lowercase. Resulting in all delivery tests failing.

Along the way I ran into some other issues including references to a tag version ":0.2.7" that I don't have in my repo and I figure setting it to ":latest" fixes my issue (and probably other folks as well).

**Comment by joshgav** [comment]
Fixed by #169, thanks @MxNxPx!
