### ISSUE TITLE
helm ingress broken

### ISSUE THREAD

**Issue by MxNxPx** [podtato-head/podtato-head#173]
The podtato-head entry service port info should be used for the helm ingress and not ["service.port"](https://github.com/podtato-head/podtato-head/blob/ec00f1427ba41acc3fae86858392655d3d320f10/delivery/chart/templates/ingress.yaml#L3) as that was from the old setup.  Also, per the [k8s deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122), and an example updated helm create command, the apiVersion logic should be changed since the removed of the extensions/v1beta1 and networking.k8s.io/v1beta1 versions in k8s v1.22.

**Comment by joshgav** [comment]
Fixed by #174. Thanks @MxNxPx !
