### ISSUE TITLE
service URLs in configmap not consistent with service names

### ISSUE THREAD

**Issue by jkleinlercher** [podtato-head/podtato-head#184]
Problem: if I install the helm-chart with a different Release.Name than "podtato-head", the arms and legs microservices are not found in the podtato-head-entry pod.

Error message:

`Get "[http://podtato-head-left-arm:9003/images/left-arm.svg":](http://podtato-head-left-arm:9003/images/left-arm.svg%22:) dial tcp: lookup podtato-head-left-arm on 10.43.0.10:53: no such host`

Reason:
The service URLs defined in the [configmap](https://github.com/podtato-head/podtato-head/blob/main/delivery/chart/templates/configmap-discovery.yaml#L12-L16) are hard coded to "http://podtato-head-<servicename>" which is only correct when the Release.Name is "podtato-head". 
The logic how the service name is built is here https://github.com/podtato-head/podtato-head/blob/main/delivery/chart/templates/service-left-arm.yaml#L8 and here https://github.com/podtato-head/podtato-head/blob/main/delivery/chart/templates/_helpers.tpl#L8-L24.

So maybe the configmap-discovery also needs this logic to define the correct names in the configmap?

**Comment by joshgav** [comment]
Thanks @jkleinlercher - I submitted #187 to fix, PTAL!
