### ISSUE TITLE
Extend podtato head to multiple services. 

### ISSUE THREAD

**Issue by AloisReitbauer** [podtato-head/podtato-head#8]

**Comment by AloisReitbauer** [comment]
From Guillaume Dupin

Also have an idea to propose to "explode" mister pod-tato-head image into several parts to easily show version updates. For example :
v0.1.0 = all parts separated ("fully-exploded" pod-tato)
v0.1.1 = some parts (arm, leg, nose...) attached
v0.1.2 = all parts attached ("complete" pod-tato)
Let me know what you think, and I'll make a PR if you think it can be fun and useful :wink:

**Comment by yogeek** [comment]
Thank you @AloisReitbauer ! (if you add the graphics with the individual parts into the repo, I will see if I have the time to make the PR)

**Comment by AloisReitbauer** [comment]
They are at here images/podtato-head-assests.  We can work on the development branch

**Comment by AloisReitbauer** [comment]
I have a first idea how to structure the example

**Comment by AloisReitbauer** [comment]
Here is an idea how to break this into individual services

![image](https://user-images.githubusercontent.com/478193/112872909-378ce300-90c1-11eb-8c23-b13891a38855.png)

**Comment by joshgav** [comment]
I believe the first round of this is complete. See #120 for a proposal to further refactor.
